### ISSUE TITLE
Getting 403

### ISSUE THREAD

**Issue by avneesh123** [agorapulse/grails-aws-sdk#62] opened 2018-01-03 20:26 UTC
I don't have permission to list queue names [ AmazonSQSClient.listQueues] but have permission to send message/receive messages from specific queue. But because of listing queue names I am getting 403.

I was able to  sent/receive message directly using AmazonSQSClient sendMessage(....) ...

Exception trace:

com.amazonaws.services.sqs.model.AmazonSQSException: Access to the resource https://sqs.us-east-1.amazonaws.com/ is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: 586aa9b5-fe97-585a-j765-fb72c2fc0746)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1629)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1605)
	at com.amazonaws.services.sqs.AmazonSQSClient.listQueues(AmazonSQSClient.java:1064)
	at com.amazonaws.services.sqs.AmazonSQS$listQueues.call(Unknown Source)
	at grails.plugin.awssdk.sqs.AmazonSQSService.loadQueues(AmazonSQSService.groovy:297)
	at grails.plugin.awssdk.sqs.AmazonSQSService.getQueueUrl(AmazonSQSService.groovy:150)
	at grails.plugin.awssdk.sqs.AmazonSQSService.getQueueUrl(AmazonSQSService.groovy)
	at grails.plugin.awssdk.sqs.AmazonSQSService.sendMessage(AmazonSQSService.groovy:250)
	at grails.plugin.awssdk.sqs.AmazonSQSService.sendMessage(AmazonSQSService.groovy)
	at grails.plugin.awssdk.sqs.AmazonSQSService.sendMessage(AmazonSQSService.groovy:268)
	at grails.plugin.awssdk.sqs.AmazonSQSService$sendMessage.call(Unknown Source)
	at our.awesome.cms.TwitterService.postArticleToTwitter(TwitterService.groovy:13)
	at sun.reflect.GeneratedMethodAccessor468.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
	at grails.events.subscriber.MethodSubscriber.call(MethodSubscriber.groovy:51)
	at org.grails.events.EventSubscriberTrigger.proceed(EventSubscriberTrigger.groovy:31)
	at org.grails.events.bus.ExecutorEventBus$_buildNotificationCallable_closure1$_closure3.doCall(ExecutorEventBus.groovy:36)
	at org.grails.events.bus.ExecutorEventBus$_buildNotificationCallable_closure1$_closure3.call(ExecutorEventBus.groovy)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by avneesh123** [comment] 2018-01-03 22:14
Its failing in - AmazonSQSService.groovy below method
 In getQueueUrl - queueUrlByNames has size zero so it call loadQueues() where it getting 403 from AmazonSQSClient listQueues() method.

**Comment by musketyr** [comment] 2018-01-05 08:59
this is duplicate of #60. if you use queue URL instead of name to bypass the queue listing

**Closed by musketyr** 2018-01-05 08:59 UTC
