### ISSUE TITLE
Didn't work with the Grails Async Framework

### ISSUE THREAD

**Issue by kevintanhongann** [agorapulse/grails-aws-sdk#67] opened 2018-01-23 06:33 UTC
Didn't work with the Grails Async Framework. 

`class AsyncAmazonS3Service {
    @DelegateAsync
    AmazonS3Service amazonS3Service
}`

```
Caused by: org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class haulage.project.async.AsyncAmazonS3Service] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetException
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:170)
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:825)
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:517)
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:788)
        at grails.boot.config.GrailsApplicationPostProcessor.performGrailsInitializationSequence(GrailsApplicationPostProcessor.groovy:112)
        at grails.boot.config.GrailsApplicationPostProcessor.initializeGrailsApplication(GrailsApplicationPostProcessor.groovy:94)
        at grails.boot.config.GrailsApplicationPostProcessor.setApplicationContext(GrailsApplicationPostProcessor.groovy:225)
        at grails.boot.config.GrailsApplicationPostProcessor.<init>(GrailsApplicationPostProcessor.groovy:78)
        at grails.boot.config.GrailsAutoConfiguration.grailsApplicationPostProcessor(GrailsAutoConfiguration.groovy:68)
        at haulage.angular.profile.Application.grailsApplicationPostProcessor(Application.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
        ... 24 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1076)
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:161)
        ... 39 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.sun.beans.TypeResolver.resolve(TypeResolver.java:203)
        at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
        at com.sun.beans.TypeResolver.resolve(TypeResolver.java:169)
        at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
        at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:96)
        at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
        at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:116)
        at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
        at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
        at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1205)
        at java.beans.Introspector.getBeanInfo(Introspector.java:426)
        at java.beans.Introspector.getBeanInfo(Introspector.java:173)
        at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3313)
        at java.security.AccessController.doPrivileged(Native Method)
        at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3311)
        at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3288)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:260)
        at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:302)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:261)
        at org.grails.datastore.mapping.reflect.ClassPropertyFetcher.getStaticPropertyValue(ClassPropertyFetcher.java:176)
        at org.grails.core.AbstractGrailsClass.getStaticPropertyValue(AbstractGrailsClass.java:239)
        at org.grails.core.DefaultGrailsServiceClass.<init>(DefaultGrailsServiceClass.java:34)
        ... 44 common frames omitted
```

**Comment by kevintanhongann** [comment] 2018-01-23 06:48
I really hope that I can do this as well.

        `asyncAmazonS3Service.storeFile('transport-request/rft-number/gate-pass/', tmpFile, CannedAccessControlList.PublicRead).onComplete {
          transportRequest.gatePassImgUrl = it
        }.onError { Throwable err ->
          respond status: HttpStatus.INTERNAL_SERVER_ERROR, message: err.message
        }`

**Comment by musketyr** [comment] 2018-01-23 07:52
can you, please, provide full stack trace of that error?

**Comment by kevintanhongann** [comment] 2018-01-23 08:22
@musketyr Edited. Sorry about that.

**Comment by musketyr** [comment] 2018-01-23 09:18
thanks. there are few more things I need to ask you:

What version of Grails and Grails Async are you using?
From which package is `@DelegateAsync` coming?

**Comment by kevintanhongann** [comment] 2018-01-23 11:50
`"org.grails.plugins:async"`

and Grails v3.3.2. The plugin version is the same with Grails version. Thanks.

**Comment by kevintanhongann** [comment] 2018-01-23 12:01
Additional info: I was using the Grails REST API profile.

**Comment by musketyr** [comment] 2018-02-09 15:26
I sadly still can't reproduce it.

https://github.com/musketyr/aws332delegate/blob/master/src/test/groovy/aws/AsyncS3ServiceSpec.groovy

Let me know if you are able to reproduce the problem in that sample repository.

Thank you.

**Comment by musketyr** [comment] 2019-01-03 11:44
I'm closing the issue for now. Feel free to reopen if you are able to reproduce the issue.

**Closed by musketyr** 2019-01-03 11:44 UTC
